### ISSUE TITLE
Feature Request: ODCR

### ISSUE THREAD

**Issue by sean-smith** [aws/aws-parallelcluster-ui#190]
This feature request is to add support for ODCR's in the UI. This is important for our machine learning customers.

See https://ml.hpcworkshops.com/03-cluster/02-odcr.html for an example of how it's added to the config.

You also need to modify the cluster template to single instance format, i.e.

```yaml
# this works
InstanceType: p4de.24xlarge
# this doesn't work
Instances:
  - InstanceType: p4de.24xlarge
```
