### ISSUE TITLE
Feature Request: Retain FSx Lustre on Delete

### ISSUE THREAD

**Issue by sean-smith** [aws/aws-parallelcluster-ui#70]
## Description
Support [DeletionPolicy: [Delete/Retain]](https://docs.aws.amazon.com/parallelcluster/latest/ug/SharedStorage-v3.html#yaml-SharedStorage-FsxLustreSettings-DeletionPolicy) flag for FSx Lustre, EFS. 

```yaml
- MountDir: /shared
    Name: efs
    StorageType: Efs
    EfsSettings:
      DeletionPolicy: Retain
  - MountDir: /fsx
    Name: fsx
    StorageType: FsxLustre
    FsxLustreSettings:
      StorageCapacity: 1200
      DeploymentType: PERSISTENT_2
      PerUnitStorageThroughput: 125
      DeletionPolicy: Retain
```

This is already done for EBS: 
<img width="677" alt="image" src="https://user-images.githubusercontent.com/5545980/221279852-cd445dfa-5e57-47d6-b4db-2826dd27a0d5.png">
